In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

In [2]:
import nltk#nltk stands fro natural language tool kit,that helps machine providing some english words to understand the senitments of the user
from nltk.corpus import stopwords #corpus is like a bag or a group that is consisted with different kinds of english words
from nltk.stem import PorterStemmer #porterstemmer is a python library that helps the machine to break the words into root forms
import string #string is that kind of a library in python that helps machine read ecah and every word as token in sentence

In [3]:
df = pd.read_csv('/content/sentiment_data.csv')

In [4]:
df

,Unnamed: 0,Comment,Sentiment
0,0,lets forget apple pay required brand new iphon...,1.0
1,1,nz retailers don’t even contactless credit car...,0.0
2,2,forever acknowledge channel help lessons ideas...,2.0
3,3,whenever go place doesn’t take apple pay doesn...,0.0
4,4,apple pay convenient secure easy use used kore...,2.0
...,...,...,...
89246,90024,modi gave â¹ rahul promises â kejri bua bhat...,2.0
89247,90025,fake claim modi didnt say would give lakhs per...,0.0
89248,90026,editorial suitboot sarkar nyay congressâ att...,2.0
89249,90027,à¥ congress à¥ à¥à¤¾ à¤¿à¤¾ wait nirav modi...,0.0
89250,90028,income person earns accounted books congress m...,NaN

In [5]:
import nltk
nltk.download('stopwords')
stop_words = stopwords.words("english")
ps = PorterStemmer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [6]:
def preprocessing (text):
    if not isinstance(text, str):
        return "" # Return an empty string or handle as appropriate for non-string types

    text = text.lower()

    token = nltk.word_tokenize(text)

    new = []

    for i in token:

       if i not in stop_words and i not in string.punctuation:

         stemmer = ps.stem(i)

         new.append(stemmer)

    return" ".join(new)

In [7]:
import nltk
nltk.download('punkt_tab')
df["clean"] = df["Comment"].apply(preprocessing)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [8]:
df["clean"]

0        let forget appl pay requir brand new iphon ord...
1        nz retail ’ even contactless credit card machi...
2        forev acknowledg channel help lesson idea expl...
3        whenev go place ’ take appl pay ’ happen often...
4        appl pay conveni secur easi use use korean jap...
                               ...
89246    modi gave â¹ rahul promis â kejri bua bhatij...
89247    fake claim modi didnt say would give lakh pers...
89248    editori suitboot sarkar nyay congressâ attac...
89249    à¥ congress à¥ à¥à¤¾ à¤¿à¤¾ wait nirav modi...
89250    incom person earn account book congress manag ...
Name: clean, Length: 89251, dtype: object

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Drop rows with NaN values in 'Sentiment'
df_cleaned = df.dropna(subset=['Sentiment'])

vector = TfidfVectorizer()

X = vector.fit_transform(df_cleaned["clean"])
y = df_cleaned["Sentiment"]

In [14]:
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,

random_state=55)

In [16]:
log = LogisticRegression()

log.fit(X_train,y_train)

LogisticRegression()

In [17]:
print("train accuracy", log.score(X_train,y_train))

print("test accuracy", log.score(X_test,y_test))

train accuracy 0.8079071628651461
test accuracy 0.7165266106442577

In [26]:
def pred_text(text):
    text = text.lower()
    text = preprocessing(text)
    vec = vector.transform([text])
    predict = log.predict(vec)[0]
    if predict == 1:
        return "negative"
    else:
        return "positive"

In [27]:
print(pred_text("i enjoy this enjoyment"))

positive

In [28]:
print(pred_text("a plane crashed yesterday"))

negative